# Known to build in Ubuntu 18.04
name: meshlab
base: core18
version: '2020.09'
summary: MeshLab
description: |
  The open source system for processing and editing 3D triangular meshes.
  It provides a set of tools for editing, cleaning, healing, inspecting,
  rendering, texturing and converting meshes. It offers features for processing
  raw data produced by 3D digitization tools/devices and for preparing models
  for 3D printing.
icon: meshlab.png

grade: stable
confinement: strict

apps:
  meshlab:
    command: desktop-launch $SNAP/AppRun
    plugs: [home, x11, mir, opengl, removable-media]
    desktop: usr/share/applications/meshlab.desktop


parts:
  desktop-qt5:
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    make-parameters:
      - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libqt5qml5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - try:
        - appmenu-qt5
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5
  meshlab:
    after: [desktop-qt5]
    plugin: qmake
    qt-version: qt5
    source: https://github.com/cnr-isti-vclab/meshlab.git
    build-packages:
      - qt5-default
      - qttools5-dev-tools
      - qtdeclarative5-dev
      - libqt5xmlpatterns5-dev
      - mesa-common-dev
      - libglu1-mesa-dev
      - lib3ds-dev
      - libglew-dev
      - libeigen3-dev
      - libopenctm-dev
      - libgmp-dev
      - libqhull-dev
      - chrpath
    stage-packages:
      - lib3ds-1-3
      - libgomp1
      - libopenctm1
      - libqhull7
      - libglew-dev
      - libqt5opengl5-dev
      - qtdeclarative5-dev
      - libqt5xmlpatterns5-dev
      - libqt5gui5
    override-build: |
      sh scripts/Linux/1_build.sh
      sh scripts/Linux/resources/make_bundle.sh

      rsync -av src/install/* $SNAPCRAFT_PART_INSTALL/

      rm $SNAPCRAFT_PART_INSTALL/usr/share/applications/meshlab.desktop
      cp scripts/Linux/resources/snap/meshlab.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications/
      cp scripts/Linux/resources/AppRunMeshLab $SNAPCRAFT_PART_INSTALL/
      mv $SNAPCRAFT_PART_INSTALL/AppRunMeshLab $SNAPCRAFT_PART_INSTALL/AppRun
      chmod +x $SNAPCRAFT_PART_INSTALL/AppRun
