# Known to build in Ubuntu 17.04
name: meshlab
version: '2017.03-1'
summary: MeshLab
description: |
  The open source system for processing and editing 3D triangular meshes.
  It provides a set of tools for editing, cleaning, healing, inspecting,
  rendering, texturing and converting meshes. It offers features for processing
  raw data produced by 3D digitization tools/devices and for preparing models
  for 3D printing.
icon: snap/gui/meshlab.png

grade: stable
confinement: devmode

apps:
  meshlab:
    command: desktop-launch meshlab
    plugs: [home, x11, mir, opengl, unity7]
  meshlabserver:
    command: desktop-launch meshlabserver
    plugs: [home, x11, opengl]

parts:
  meshlab:
    after: [desktop-qt5,vcglib]
    plugin: qmake
    qt-version: qt5
    source: https://github.com/cnr-isti-vclab/meshlab.git
    build-packages:
      - libqt5opengl5-dev
      - libqt5xmlpatterns5-dev
      - qt5-default
      - qtscript5-dev
    prepare: |
      ln -sf ../vcglib/install ../vcglib 
      sed -i '/filter_csg/d' src/meshlab_full.pro
      sed -i -e '2ilinux:QMAKE_LFLAGS += -fopenmp -lgomp\' src/meshlabplugins/filter_screened_poisson/filter_screened_poisson.pro
      sed -i 's|PR_XXXXXX|/tmp/PR_XXXXXX|' src/meshlabplugins/filter_screened_poisson/Src/Geometry.cpp
    build: |
      cd src/external
      qmake external.pro
      make -j4
      cd ..
      qmake meshlab_full.pro
      make -j4
    install: |
      cp src/meshlabplugins/filter_screened_poisson/filter_screened_poisson.xml \
          src/meshlabplugins/filter_mutualinfoxml/filter_mutualinfo.xml \
          src/meshlabplugins/filter_measure/filter_measure.xml \
          src/distrib/plugins/
      cd src/distrib
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -a meshlab* plugins shaders textures $SNAPCRAFT_PART_INSTALL/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/lib
      cp -a lib* $SNAPCRAFT_PART_INSTALL/lib
  vcglib:
    plugin: dump
#    source: https://github.com/cnr-isti-vclab/vcglib.git
#    source-tag: v1.0.2
    source: https://github.com/cnr-isti-vclab/vcglib.git
    source-branch: devel
    - -vcglib/apps  
    prime: [ -* ]

