######################################################################
# Automatically generated by qmake (2.00a) ven 24. giu 14:14:20 2005
######################################################################
#  To solve issue related to slash vs. backslash under cygwin try:
#  env MINGW_IN_SHELL=1 qmake -spec win32-g++ 

TARGET = curvature
LIBPATH += 
DEPENDPATH += . 
INCLUDEPATH += . ../../../../sf/
CONFIG += console stl
TEMPLATE = app
HEADERS += curvature.h
SOURCES += curvature.cpp