######################################################################
# Automatically generated by qmake (2.00a) mer feb 1 14:17:15 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += QEdgeLength.h ui_edgeLengthDialog.h
SOURCES += main.cpp QEdgeLength.cpp
