######################################################################
# Automatically generated by qmake (2.00a) ven 24. giu 14:14:20 2005
######################################################################

TARGET = trimesh_SS
LIBPATH += 
DEPENDPATH += . 
INCLUDEPATH += . ../../../../sf/
CONFIG += console stl 
TEMPLATE = app
SOURCES += new_refine.h trimesh_smooth.cpp ../../../../sf/wrap/ply/plylib.cpp