######################################################################
# Automatically generated by qmake (2.00a) ven 24. giu 14:14:20 2005
######################################################################

TARGET = curvature
LIBPATH += 
DEPENDPATH += . 
INCLUDEPATH += . ../../../sf
CONFIG += console stl
TEMPLATE = app
SOURCES += curvature.cpp
