######################################################################
# Automatically generated by qmake (2.00a) gio nov 17 10:51:02 2005
######################################################################


TEMPLATE      = lib
CONFIG       += plugin
INCLUDEPATH  += . ../../../../sf
HEADERS += export_obj.h import_obj.h
SOURCES += io.cpp
TARGET        = io
DESTDIR       = ../../meshlab/plugins
                                                                                                                           
contains(TEMPLATE,lib) {
   CONFIG(debug, debug|release) {
      unix:TARGET = $$member(TARGET, 0)_debug
      else:TARGET = $$member(TARGET, 0)d
   }
}
