######################################################################
# Automatically generated by qmake (1.07a) Tue Nov 8 22:02:48 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += . ../../../../sf/

# Input
HEADERS += export_obj.h import_obj.h
SOURCES += io.cpp
