// This file was generated by qlalr - DO NOT EDIT!
#ifndef JS_GRAMMAR_P_H
#define JS_GRAMMAR_P_H

class js_grammar
{
public:
  enum VariousConstants {
    EOF_SYMBOL = 0,
    T_AND = 1,
    T_AND_AND = 2,
    T_AND_EQ = 3,
    T_BREAK = 4,
    T_CASE = 5,
    T_CATCH = 6,
    T_COLON = 7,
    T_COMMA = 8,
    T_CONST = 79,
    T_CONTINUE = 9,
    T_DEBUGGER = 80,
    T_DEFAULT = 10,
    T_DELETE = 11,
    T_DIVIDE_ = 12,
    T_DIVIDE_EQ = 13,
    T_DO = 14,
    T_DOT = 15,
    T_ELSE = 16,
    T_EQ = 17,
    T_EQ_EQ = 18,
    T_EQ_EQ_EQ = 19,
    T_FALSE = 78,
    T_FINALLY = 20,
    T_FOR = 21,
    T_FUNCTION = 22,
    T_GE = 23,
    T_GT = 24,
    T_GT_GT = 25,
    T_GT_GT_EQ = 26,
    T_GT_GT_GT = 27,
    T_GT_GT_GT_EQ = 28,
    T_IDENTIFIER = 29,
    T_IF = 30,
    T_IN = 31,
    T_INSTANCEOF = 32,
    T_LBRACE = 33,
    T_LBRACKET = 34,
    T_LE = 35,
    T_LPAREN = 36,
    T_LT = 37,
    T_LT_LT = 38,
    T_LT_LT_EQ = 39,
    T_MINUS = 40,
    T_MINUS_EQ = 41,
    T_MINUS_MINUS = 42,
    T_NEW = 43,
    T_NOT = 44,
    T_NOT_EQ = 45,
    T_NOT_EQ_EQ = 46,
    T_NULL = 76,
    T_NUMERIC_LITERAL = 81,
    T_OR = 47,
    T_OR_EQ = 48,
    T_OR_OR = 49,
    T_PLUS = 50,
    T_PLUS_EQ = 51,
    T_PLUS_PLUS = 52,
    T_QUESTION = 53,
    T_RBRACE = 54,
    T_RBRACKET = 55,
    T_REMAINDER = 56,
    T_REMAINDER_EQ = 57,
    T_RESERVED_WORD = 82,
    T_RETURN = 58,
    T_RPAREN = 59,
    T_SEMICOLON = 60,
    T_STAR = 61,
    T_STAR_EQ = 62,
    T_STRING_LITERAL = 63,
    T_SWITCH = 64,
    T_THIS = 65,
    T_THROW = 66,
    T_TILDE = 67,
    T_TRUE = 77,
    T_TRY = 68,
    T_TYPEOF = 69,
    T_VAR = 70,
    T_VOID = 71,
    T_WHILE = 72,
    T_WITH = 73,
    T_XOR = 74,
    T_XOR_EQ = 75,

    ACCEPT_STATE = 236,
    RULE_COUNT = 259,
    STATE_COUNT = 458,
    TERMINAL_COUNT = 83,
    NON_TERMINAL_COUNT = 88,

    GOTO_INDEX_OFFSET = 458,
    GOTO_INFO_OFFSET = 1442,
    GOTO_CHECK_OFFSET = 1442
  };

  static const char  *const    spell [];
  static const short             lhs [];
  static const short             rhs [];

#ifndef QLALR_NO_JS_GRAMMAR_DEBUG_INFO
  static const int     rule_index [];
  static const int      rule_info [];
#endif // QLALR_NO_JS_GRAMMAR_DEBUG_INFO

  static const short    goto_default [];
  static const short  action_default [];
  static const short    action_index [];
  static const short     action_info [];
  static const short    action_check [];

  static inline int nt_action (int state, int nt)
  {
    const int yyn = action_index [GOTO_INDEX_OFFSET + state] + nt;
    if (yyn < 0 || action_check [GOTO_CHECK_OFFSET + yyn] != nt)
      return goto_default [nt];

    return action_info [GOTO_INFO_OFFSET + yyn];
  }

  static inline int t_action (int state, int token)
  {
    const int yyn = action_index [state] + token;

    if (yyn < 0 || action_check [yyn] != token)
      return - action_default [state];

    return action_info [yyn];
  }
};


#endif // JS_GRAMMAR_P_H

