
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 92
#define YY_END_OF_BUFFER 93
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[214] =
    {   0,
        0,    0,   93,   92,   91,   44,   55,    3,   37,   57,
       60,   50,    8,   40,   15,   13,   78,   78,    7,   58,
       36,   19,   27,   51,   90,   32,   53,   73,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       31,   47,   52,   65,   43,   54,    1,    2,   59,   49,
       48,   38,   39,   86,    0,   61,   12,    0,   86,   78,
        0,    0,   82,   79,    0,   82,   78,   34,   35,   18,
       25,   26,   90,   90,   72,   90,   90,   90,   90,   14,
       90,   90,   90,   90,   90,   28,   29,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   45,   46,

       42,    0,   86,    0,   87,   84,   81,   80,   80,    0,
       78,   33,   17,   24,    0,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   21,   90,   90,   41,   90,   90,
       90,   90,   90,   90,   66,   90,   68,   90,   90,   90,
        0,   86,   87,   85,   83,    0,    0,    0,   23,   90,
        5,   90,   90,   90,   90,   90,   16,   90,   90,   90,
       90,   74,   90,   90,   63,   90,   75,   90,   69,   90,
       71,    0,    0,   89,    4,    6,   77,   90,   90,   90,
       76,   90,   90,   90,   90,   90,   64,   90,   70,    0,
       88,   89,   90,   90,   11,   90,   90,   90,   56,   62,

       67,   88,   90,   10,   20,   90,   90,    9,   22,   90,
       90,   30,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   17,
       17,   17,   17,   17,   17,   18,   18,   19,   20,   21,
       22,   23,   24,    1,   25,   25,   25,   25,   26,   27,
       28,   28,   28,   28,   28,   29,   28,   28,   28,   30,
       28,   28,   28,   28,   31,   28,   28,   32,   28,   28,
       33,   34,   35,   36,   37,    1,   38,   39,   40,   41,

       42,   43,   28,   44,   45,   28,   46,   47,   28,   48,
       49,   50,   28,   51,   52,   53,   54,   55,   56,   32,
       57,   28,   58,   59,   60,   61,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[62] =
    {   0,
        1,    1,    1,    1,    2,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    1,    4,    4,    4,    1,    1,
        1,    1,    1,    1,    4,    4,    4,    5,    5,    5,
        5,    5,    1,    1,    1,    1,    5,    4,    4,    4,
        4,    4,    4,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    1,    1,    1,
        1
    } ;

static yyconst flex_int16_t yy_base[219] =
    {   0,
        0,    0,  240,  801,  801,  211,  203,   55,  801,  801,
      191,   52,  801,   51,   49,   53,   74,   53,  801,  801,
       57,  177,   58,  801,   66,  801,  801,  165,   78,   81,
       91,   94,   97,  106,  120,  127,  109,  139,  114,  122,
      801,   80,  801,  801,  142,  801,  801,  801,  801,  801,
      801,  801,  801,  162,   86,  116,  119,  167,  168,  129,
      200,  190,  144,   57,  134,  146,    0,  125,  801,  110,
      801,   95,    0,  203,  801,  206,  211,  214,  218,  221,
      227,  233,  236,  239,  250,  242,  253,  256,  259,  265,
      269,  275,  278,  283,  286,  291,  299,  305,  801,  801,

      801,  329,  801,  311,  332,  127,  801,   64,   42,    0,
      324,  801,  801,  801,   54,  346,  349,  352,  364,  369,
      372,  377,  380,  383,  386,  393,  406,  409,  413,  418,
      421,  424,  428,  431,  434,  437,  440,  445,  448,  452,
      464,  471,  801,  801,  801,  152,  162,  486,  801,  467,
      474,  489,  492,  499,  503,  506,  509,  512,  518,  521,
      524,  530,  533,  550,  553,  559,  562,  565,  569,  575,
      578,  586,  589,  592,  595,  606,  609,  612,  615,  624,
      620,  627,  630,  633,  636,  639,  647,  651,  654,  660,
      669,  801,  672,  675,  683,  686,  689,  692,  697,  701,

      704,  801,  707,  713,  717,  723,  728,  734,  737,  740,
      743,  746,  801,  789,  791,  794,  795,   68
    } ;

static yyconst flex_int16_t yy_def[219] =
    {   0,
      213,    1,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  214,  213,   17,  213,  213,
      213,  213,  213,  213,  215,  213,  213,  213,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,   33,   33,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  214,  214,  214,  214,  213,   17,
      213,  213,  213,  213,  216,  213,   18,  213,  213,  213,
      213,  213,  217,  215,  213,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  213,  213,

      213,  213,  213,  213,  213,  213,  213,  213,  213,  218,
      216,  213,  213,  213,  213,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      213,  213,  213,  213,  213,  218,  218,  213,  213,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  213,  213,  213,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  213,
      213,  213,  215,  215,  215,  215,  215,  215,  215,  215,

      215,  213,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,    0,  213,  213,  213,  213,  213
    } ;

static yyconst flex_int16_t yy_nxt[863] =
    {   0,
        4,    5,    5,    6,    4,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   18,   19,   20,
       21,   22,   23,   24,   25,   25,   25,   25,   25,   25,
       25,   25,   26,    4,   27,   28,   25,   25,   29,   30,
       31,   32,   33,   25,   34,   25,   25,   35,   25,   25,
       36,   37,   38,   25,   39,   40,   25,   41,   42,   43,
       44,   47,   50,   52,   54,   54,   54,   56,   67,   67,
       67,  146,   53,   51,   57,  149,   48,   68,   69,   71,
       72,   73,   73,   73,  213,  108,   58,   59,  145,   60,
       60,   61,  145,   73,   73,   73,   73,   73,   73,   62,

       56,   99,   63,  109,   64,   65,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   62,  114,  115,   77,   58,
       66,   73,   73,   73,   73,   73,   73,   64,   76,   78,
       56,  113,   79,   56,   82,   73,   73,   73,  100,   80,
       81,   83,   73,   73,   73,   84,  112,  110,   86,   58,
       85,   95,   58,   87,   73,   73,   73,  144,   74,   74,
      213,   88,   96,  101,   91,   97,   98,   74,   90,  213,
       74,   55,  106,   89,  107,   74,  107,   54,   54,   54,
      144,  172,   92,   54,   54,   54,   75,  102,  103,   93,
      103,  172,  106,  102,  103,   94,  103,  107,   70,  107,

      104,  172,  104,  102,  103,  105,  105,  105,  103,  102,
      103,  172,   49,   59,  103,   61,   61,   61,   73,   73,
       73,   73,   73,   73,   46,   62,   73,   73,   73,   73,
       73,   73,   45,   73,   73,   73,   73,   73,   73,  213,
      213,   62,   73,   73,   73,  213,  213,  116,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
      120,  119,  117,  118,  121,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,  213,  122,  123,
       73,   73,   73,  124,   73,   73,   73,  213,  213,  125,
       73,   73,   73,   73,   73,   73,  213,  126,   73,   73,

       73,   73,   73,   73,  127,  129,   73,   73,   73,  213,
      213,  128,  213,  131,   73,   73,   73,  130,  213,  132,
       73,   73,   73,  213,  213,  133,  105,  105,  105,  213,
      213,  134,  136,  213,  135,  138,  137,  147,  213,  141,
      213,  141,  213,  139,  142,  142,  142,  105,  105,  105,
      213,  213,   63,  148,   64,  213,  213,  140,  143,  213,
      143,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       66,  213,  213,  148,  143,  213,  213,   64,  143,   73,
       73,   73,  213,  150,   73,   73,   73,   73,   73,   73,
      151,  152,   73,   73,   73,   73,   73,   73,   73,   73,

       73,   73,   73,   73,  213,  213,  155,  213,   73,   73,
       73,  213,  213,  156,  213,  153,  154,  213,  157,  213,
      159,   73,   73,   73,   73,   73,   73,  213,   73,   73,
       73,  158,  160,   73,   73,   73,   73,   73,   73,   73,
       73,   73,  213,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,  161,  162,
       73,   73,   73,   73,   73,   73,  213,   73,   73,   73,
      213,  163,  167,  164,  213,  165,  166,  213,  168,  142,
      142,  142,   73,   73,   73,  169,  142,  142,  142,   73,
       73,   73,  213,  213,  170,  171,  173,  103,  173,  103,

      213,  174,  174,  174,   73,   73,   73,   73,   73,   73,
      213,  213,  175,  103,   73,   73,   73,  103,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
      213,  213,  176,   73,   73,   73,   73,   73,   73,   73,
       73,   73,  213,  178,  177,   73,   73,   73,   73,   73,
       73,  213,  213,  181,  213,  213,  179,  213,  180,  213,
      213,  184,  213,  213,  182,   73,   73,   73,   73,   73,
       73,  213,  213,  183,   73,   73,   73,   73,   73,   73,
       73,   73,   73,  185,   73,   73,   73,  213,  213,  186,
       73,   73,   73,   73,   73,   73,  190,  213,  190,  213,

      213,  191,  191,  191,  174,  174,  174,  174,  174,  174,
       73,   73,   73,  188,  187,  213,  189,  213,  192,  213,
      192,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,  213,  192,   73,   73,   73,  192,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,  213,  213,  193,
      213,  194,   73,   73,   73,  195,   73,   73,   73,   73,
       73,   73,  213,  196,  197,  191,  191,  191,  213,  213,
      198,  213,  200,  199,  191,  191,  191,   73,   73,   73,
       73,   73,   73,  201,  213,  202,  213,  202,   73,   73,

       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
      213,  202,   73,   73,   73,  202,   73,   73,   73,   73,
       73,   73,   73,   73,   73,  203,  213,  204,   73,   73,
       73,  207,   73,   73,   73,  213,  213,  206,   73,   73,
       73,  213,  205,   73,   73,   73,  213,  213,  208,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,  213,  213,  213,  213,  213,  210,
      209,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  212,  213,  213,  211,   55,
      213,   55,   55,   55,   74,   74,  111,  111,   73,   73,

        3,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213
    } ;

static yyconst flex_int16_t yy_chk[863] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    8,   12,   14,   15,   15,   15,   16,   18,   18,
       18,  218,   14,   12,   16,  115,    8,   21,   21,   23,
       23,   25,   25,   25,   18,   64,   16,   17,  109,   17,
       17,   17,  108,   29,   29,   29,   30,   30,   30,   17,

       55,   42,   17,   64,   17,   17,   31,   31,   31,   32,
       32,   32,   33,   33,   33,   17,   72,   72,   30,   55,
       17,   34,   34,   34,   37,   37,   37,   17,   29,   30,
       56,   70,   31,   57,   33,   35,   35,   35,   42,   31,
       32,   33,   36,   36,   36,   33,   68,   65,   34,   56,
       33,   39,   57,   34,   38,   38,   38,  106,   39,   40,
       60,   35,   39,   45,   37,   40,   40,   39,   36,   58,
       40,   58,   63,   35,   63,   40,   66,   54,   54,   54,
      106,  146,   38,   59,   59,   59,   28,   54,   54,   38,
       54,  147,   66,   59,   59,   38,   59,   63,   22,   66,

       62,  146,   62,   54,   54,   62,   62,   62,   54,   59,
       59,  147,   11,   61,   59,   61,   61,   61,   74,   74,
       74,   76,   76,   76,    7,   61,   77,   77,   77,   78,
       78,   78,    6,   79,   79,   79,   80,   80,   80,    3,
        0,   61,   81,   81,   81,    0,    0,   76,   82,   82,
       82,   83,   83,   83,   84,   84,   84,   86,   86,   86,
       79,   78,   77,   77,   79,   85,   85,   85,   87,   87,
       87,   88,   88,   88,   89,   89,   89,    0,   81,   82,
       90,   90,   90,   83,   91,   91,   91,    0,    0,   84,
       92,   92,   92,   93,   93,   93,    0,   85,   94,   94,

       94,   95,   95,   95,   87,   89,   96,   96,   96,    0,
        0,   88,    0,   91,   97,   97,   97,   90,    0,   92,
       98,   98,   98,    0,    0,   92,  104,  104,  104,    0,
        0,   93,   94,    0,   93,   96,   95,  111,    0,  102,
        0,  102,    0,   97,  102,  102,  102,  105,  105,  105,
        0,    0,  111,  111,  111,    0,    0,   98,  105,    0,
      105,  116,  116,  116,  117,  117,  117,  118,  118,  118,
      111,    0,    0,  111,  105,    0,    0,  111,  105,  119,
      119,  119,    0,  116,  120,  120,  120,  121,  121,  121,
      117,  118,  122,  122,  122,  123,  123,  123,  124,  124,

      124,  125,  125,  125,    0,    0,  120,    0,  126,  126,
      126,    0,    0,  121,    0,  119,  119,    0,  122,    0,
      124,  127,  127,  127,  128,  128,  128,    0,  129,  129,
      129,  123,  126,  130,  130,  130,  131,  131,  131,  132,
      132,  132,    0,  133,  133,  133,  134,  134,  134,  135,
      135,  135,  136,  136,  136,  137,  137,  137,  127,  129,
      138,  138,  138,  139,  139,  139,    0,  140,  140,  140,
        0,  130,  134,  131,    0,  132,  133,    0,  136,  141,
      141,  141,  150,  150,  150,  138,  142,  142,  142,  151,
      151,  151,    0,    0,  139,  140,  148,  142,  148,  142,

        0,  148,  148,  148,  152,  152,  152,  153,  153,  153,
        0,    0,  150,  142,  154,  154,  154,  142,  155,  155,
      155,  156,  156,  156,  157,  157,  157,  158,  158,  158,
        0,    0,  152,  159,  159,  159,  160,  160,  160,  161,
      161,  161,    0,  154,  153,  162,  162,  162,  163,  163,
      163,    0,    0,  158,    0,    0,  155,    0,  156,    0,
        0,  161,    0,    0,  159,  164,  164,  164,  165,  165,
      165,    0,    0,  160,  166,  166,  166,  167,  167,  167,
      168,  168,  168,  163,  169,  169,  169,    0,    0,  164,
      170,  170,  170,  171,  171,  171,  172,    0,  172,    0,

        0,  172,  172,  172,  173,  173,  173,  174,  174,  174,
      175,  175,  175,  168,  166,    0,  170,    0,  174,    0,
      174,  176,  176,  176,  177,  177,  177,  178,  178,  178,
      179,  179,  179,    0,  174,  181,  181,  181,  174,  180,
      180,  180,  182,  182,  182,  183,  183,  183,  184,  184,
      184,  185,  185,  185,  186,  186,  186,    0,    0,  178,
        0,  179,  187,  187,  187,  180,  188,  188,  188,  189,
      189,  189,    0,  182,  183,  190,  190,  190,    0,    0,
      184,    0,  186,  185,  191,  191,  191,  193,  193,  193,
      194,  194,  194,  188,    0,  191,    0,  191,  195,  195,

      195,  196,  196,  196,  197,  197,  197,  198,  198,  198,
        0,  191,  199,  199,  199,  191,  200,  200,  200,  201,
      201,  201,  203,  203,  203,  193,    0,  194,  204,  204,
      204,  198,  205,  205,  205,    0,    0,  197,  206,  206,
      206,    0,  196,  207,  207,  207,    0,    0,  203,  208,
      208,  208,  209,  209,  209,  210,  210,  210,  211,  211,
      211,  212,  212,  212,    0,    0,    0,    0,    0,  207,
      206,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  211,    0,    0,  210,  214,
        0,  214,  214,  214,  215,  215,  216,  216,  217,  217,

      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "js_lex.l"
#define YY_NO_UNISTD_H 1
#line 5 "js_lex.l"
#include "js_parser.h"
#include <cstdlib>
#include <io.h>

#define YY_DECL int JSParser::nextToken()
#line 722 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 26 "js_lex.l"


#line 907 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 214 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 801 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 28 "js_lex.l"
{}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 29 "js_lex.l"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 30 "js_lex.l"
{}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 31 "js_lex.l"
{}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 32 "js_lex.l"
{}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 33 "js_lex.l"
{}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 34 "js_lex.l"
{return T_COLON;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 35 "js_lex.l"
{return T_COMMA;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 36 "js_lex.l"
{}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 37 "js_lex.l"
{}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 38 "js_lex.l"
{}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 39 "js_lex.l"
{}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 40 "js_lex.l"
{}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 41 "js_lex.l"
{}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 42 "js_lex.l"
{return T_DOT;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 43 "js_lex.l"
{}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 44 "js_lex.l"
{}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 45 "js_lex.l"
{}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 46 "js_lex.l"
{return T_EQ;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 47 "js_lex.l"
{}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 48 "js_lex.l"
{}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 49 "js_lex.l"
{return T_FUNCTION;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 50 "js_lex.l"
{}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 51 "js_lex.l"
{}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 52 "js_lex.l"
{}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 53 "js_lex.l"
{}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 54 "js_lex.l"
{}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 55 "js_lex.l"
{}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 56 "js_lex.l"
{}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 57 "js_lex.l"
{}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 58 "js_lex.l"
{return T_LBRACKET;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 59 "js_lex.l"
{return T_LBRACE;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 60 "js_lex.l"
{}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 61 "js_lex.l"
{}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 62 "js_lex.l"
{}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 63 "js_lex.l"
{}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 64 "js_lex.l"
{return T_LPAREN;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 65 "js_lex.l"
{}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 66 "js_lex.l"
{}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 67 "js_lex.l"
{}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 68 "js_lex.l"
{return T_NEW;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 69 "js_lex.l"
{}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 70 "js_lex.l"
{} 
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 71 "js_lex.l"
{}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 72 "js_lex.l"
{}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 73 "js_lex.l"
{}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 74 "js_lex.l"
{}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 75 "js_lex.l"
{}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 76 "js_lex.l"
{}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 77 "js_lex.l"
{}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 78 "js_lex.l"
{}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 79 "js_lex.l"
{return T_RBRACKET;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 80 "js_lex.l"
{return T_RBRACE;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 81 "js_lex.l"
{}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 82 "js_lex.l"
{}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 83 "js_lex.l"
{}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 84 "js_lex.l"
{return T_RPAREN;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 85 "js_lex.l"
{return T_SEMICOLON;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 86 "js_lex.l"
{}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 87 "js_lex.l"
{}
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 88 "js_lex.l"
{return T_STRING_LITERAL;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 89 "js_lex.l"
{}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 90 "js_lex.l"
{return T_THIS;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 91 "js_lex.l"
{}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 92 "js_lex.l"
{}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 93 "js_lex.l"
{}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 94 "js_lex.l"
{}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 95 "js_lex.l"
{return T_VAR;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 96 "js_lex.l"
{}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 97 "js_lex.l"
{}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 98 "js_lex.l"
{}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 99 "js_lex.l"
{}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 100 "js_lex.l"
{}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 101 "js_lex.l"
{return T_NULL;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 102 "js_lex.l"
{}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 103 "js_lex.l"
{}	
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 104 "js_lex.l"
{return T_CONST;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 106 "js_lex.l"
{yyval.i = QString(yytext).toInt();return T_NUMERIC_LITERAL;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 107 "js_lex.l"
{yyval.u = QString(yytext).toUInt();return T_NUMERIC_LITERAL;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 108 "js_lex.l"
{yyval.ul = QString(yytext).toULong();return T_NUMERIC_LITERAL;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 109 "js_lex.l"
{yyval.ul = QString(yytext).toULong();return T_NUMERIC_LITERAL;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 110 "js_lex.l"
{yyval.l = QString(yytext).toLong();return T_NUMERIC_LITERAL;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 111 "js_lex.l"
{yyval.l = QString(yytext).toULongLong();return T_NUMERIC_LITERAL;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 112 "js_lex.l"
{yyval.l = QString(yytext).toLongLong();return T_NUMERIC_LITERAL;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 113 "js_lex.l"
{yyval.l = QString(yytext).toULongLong();return T_NUMERIC_LITERAL;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 114 "js_lex.l"
{yyval.f = QString(yytext).toFloat();return T_NUMERIC_LITERAL;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 115 "js_lex.l"
{yyval.f = QString(yytext).toFloat();return T_NUMERIC_LITERAL;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 116 "js_lex.l"
{yyval.f = QString(yytext).toFloat();return T_NUMERIC_LITERAL;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 117 "js_lex.l"
{yyval.f = QString(yytext).toFloat();return T_NUMERIC_LITERAL;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 118 "js_lex.l"
{yyval.s = insert(yytext);return T_IDENTIFIER;}
	YY_BREAK
case 91:
/* rule 91 can match eol */
YY_RULE_SETUP
#line 119 "js_lex.l"
{}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 121 "js_lex.l"
ECHO;
	YY_BREAK
#line 1452 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 214 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 214 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 213);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 121 "js_lex.l"



