.TH MeshLabServer 1 "21 Feb 2020" "2020.02"
.SH NAME
MeshLabServer \- The open source batch mesh processing system
.SH SYNOPSIS
.B meshlabserver 
[logargs] [args]
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
.SH SEE ALSO
.TP 
https://github.com/cnr-isti-vclab/meshlab/blob/master/src/meshlabserver/README.md
.TP 
https://github.com/cnr-isti-vclab/meshlab/blob/master/src/meshlabserver/meshlabserver.txt
.SH AUTHOR
Paolo Cignoni - Visual Computing Lab - ISTI - CNR
